### ISSUE TITLE
INFO ABOUT SSL CERTIFICATES IN PYTHON FOR BEGINNERS 

### ISSUE THREAD

**Issue by adijdhv** [mahawiki/BackToBasics-Hacktoberfest#13]
I would like to add a file by showing SSL CERTIFICATES definitions and how to bypass it if its not present in the webpage using python because python don't allow us to access web pages with HTTPS protocol. :) I hope you would accept my pull request.

**Comment by APratham** [comment]
Yes we will.. the only thing is please read the contribution guidelines for any repository before making commits to it. This is because others will just mark it as invalid.

Can you also rename the file to something more meaningful as told on the PR #11?

**Comment by APratham** [comment]
If you are unable to rename it just let me know by commenting on this thread or ask on the group. We are always there to help you in any way we can

**Comment by adijdhv** [comment]
Hello, how to rename it to .md ? I am not able to do it. need help. I want to upload one more file for ascii values. so can I upload it with .py or .md?

**Comment by APratham** [comment]
I saw that you deleted the ASCII values file. If it is `python` code, use `.py`. Otherwise if you are just telling the steps, you can use `.md`. `.md` files have the advantage that they can be styled by using Markdown, and you can make them look way better than a normal .txt file

**Comment by adijdhv** [comment]
Yes I will try to reupload it with .py.  
actually at first when i uploaded it my hacktober wasn't considering it dont know why. so I deleted it. what was the reason ? I want to upload it but again it may happen likewise. what I should do?

**Comment by APratham** [comment]
I am not sure why it is happening. Your PRs will all appear in review period, which currently is ~14 days. That is also one of the reasons we are asking members to first create an issue, then a PR. So that the repo is not flagged by Digital Ocean for Hacktoberfest. Are you a part of the WhatsApp group? It is the best place to get your doubts cleared

**Comment by adijdhv** [comment]
No I'm new here, can I get the link pls?

**Comment by APratham** [comment]
https://chat.whatsapp.com/L6E0oL5Du9LBzrq8VQIcgD

**Comment by adijdhv** [comment]
Done Thank you !
