### ISSUE TITLE
Java basics programs

### ISSUE THREAD

**Issue by rid17pawar** [mahawiki/BackToBasics-Hacktoberfest#15]
Can we create resources for java programming language as well for beginners? 
If yes, I would like to share some basic java programs.

**Comment by APratham** [comment]
Yes sure, please go ahead. As you have already contributed to this repository before too, you know the guidelines. You will have to create /Java folder and include your resources in that. Also make sure you include a README so people who how to use the code/tutorials you have provided

**Comment by rid17pawar** [comment]
Ok thanks
