### ISSUE TITLE
Datastructures and Algorithms in Python

### ISSUE THREAD

**Issue by ShivaSankeerth** [mahawiki/BackToBasics-Hacktoberfest#16]
**Is your feature request related to a problem? Please describe.**
I would like to implement Data-structures and algorithms in the Python module of the Repository

**Describe the solution you'd like**
First, I would start with Linear Data-structures using Node as a basic unit and complete them by the end of Hacktober fest. Later, I would implement different sorting algorithms. All these implementations would be accompanied by various follow-up resources(Videos and blogs) and if possible a few practice problems.

**Comment by APratham** [comment]
That sounds wonderful. You are planning to contribute after Hacktoberfest too 😍😍

For better understanding, it will be great if you can keep all the code in a folder or something

**Comment by ShivaSankeerth** [comment]
Sure.
Should I create a folder with the name "Data Structures and Algorithms" inside the python folder?

**Comment by APratham** [comment]
It will be great if you can have a separate folder. The Python folder was just for 10 basic programs that's all. So I think you should create a new folder. Maybe we can have another folder Python and you can put all your code inside it? That is also another idea you can think of.

**Comment by ShivaSankeerth** [comment]
I was thinking of the same. Having a separate folder will work for now, but maybe in the future, we need to reorganise everything. For the time being, I submitted a pull request with everything in a separate folder. Later, we can reorganise like this. The main folder "Python". Inside that, we will have "Basics" and "DS and ALGO". We can also add any other folders depending on the nature of the contribution.

What do you think of it @APratham ?

**Comment by APratham** [comment]
Awesome. Then in basics folder we can have the basic programs too. That is great. Just as a reminder, once I merge your PR, this issue will be closed. So for further contributions you have to open other issues whenever you want to contribute and follow the same process. 

If you want to join the GitHub organisation, send yourself an invite from here: https://mahawiki-github.herokuapp.com/
