### ISSUE TITLE
Add Projects Folder

### ISSUE THREAD

**Issue by ShivaSankeerth** [mahawiki/BackToBasics-Hacktoberfest#19]
I would like to add Projects folder into "Data Structures and Algorithms using Python" Folder and include an example to solve "Towers of Hanoi" using Stacks.

**Comment by APratham** [comment]
Bro I kinda feel that it will be confusing. How about we create a separate /Projects folder outside the "Data Structures and Algorithms using Python" folder and you and even others who contribute later on can add their simple projects to that?

**Comment by ShivaSankeerth** [comment]
It's your wish bro. I thought it would be neat to include a Projects folder in each Technology so that beginners can get their hands dirty by practising the projects. Anyways, we can contribute now as part of hacktober fest and later we can re-organise everything.

Can you please add the "Hacktoberfest" label to this issue bro?

**Comment by APratham** [comment]
Done. Okay you can add /Projects folder to the DSA one. Yes once Hacktoberfest is over, we will anyway be organising this repo a little bit more

**Comment by APratham** [comment]
Hacktoberfest label was earlier thought to be required for PRs, which is why we added the label too. But they didn't go forward with that decision because then everyone will need to add the label to their repos

**Comment by ShivaSankeerth** [comment]
Yeah. Thanks for letting me know this. And also, we will make this repo one of the best by neatly organising everything a beginner will ever need to get started. Thanks for allowing me to add a projects folder under DSA one.
