### ISSUE TITLE
Coding-Interview-Problems

### ISSUE THREAD

**Issue by Shubhamnakawe** [mahawiki/BackToBasics-Hacktoberfest#22]
**I want contribute some famous coding interview problems.**

**Comment by APratham** [comment]
Sure.. no problem. It's just that this repo is meant only for basics.. and for helping beginners get started. Coding interview problems can be a bit over the top

**Comment by Shubhamnakawe** [comment]
The programs will be basics.

**Comment by APratham** [comment]
Okay then. Just make sure you are adding a README so that people can know more about the code you have written and how to execute it etc. It will be great if the code is as easy as possible.

**Comment by Shubhamnakawe** [comment]
Sure. I will do it

**Comment by Shubhamnakawe** [comment]
I will also update more problems in the folder. 
I'm working on it.

**Comment by APratham** [comment]
Up to you bro. Just make sure you are not overloading yourself because you are working on 3 different things at the same time 😅

**Comment by Shubhamnakawe** [comment]
Yes.  First  I will complete coding interview problems. and then will work on DSA python.
