### ISSUE TITLE
I want to contribute some basic DSA codes of python.

### ISSUE THREAD

**Issue by Shubhamnakawe** [mahawiki/BackToBasics-Hacktoberfest#25]

**Comment by APratham** [comment]
That sounds great. We have a PR that was going to add a `/Python` folder, but you can create it too. We also have some codes in `/Data Structures and Algorithms using Python`. Please go through them and make sure that you are not committing similar codes as it will lead to confusion

**Comment by Shubhamnakawe** [comment]
Is it fine if I add files in /Data Structures and Algorithms using Python folder.

**Comment by APratham** [comment]
Yes sure you can do that

**Comment by Shubhamnakawe** [comment]
@APratham  I have added 4 new programs in python.

Please review my PR #30

**Comment by APratham** [comment]
@Shubhamnakawe sorry about that. I was a little busy. Will do that now for sure.

**Comment by Shubhamnakawe** [comment]
Thank you for helping me.
