### ISSUE TITLE
AWS for beginners

### ISSUE THREAD

**Issue by Shubhamnakawe** [mahawiki/BackToBasics-Hacktoberfest#26]
I will explain from aws account creation to some aws services which are mostly used by developers.

**Comment by APratham** [comment]
Yes that sounds wonderful. Although it is recommended that you complete one of the issues first. If you want to work on this, by all means do. But don't work on both at the same time.

As I am not familiar with AWS, do you have some interactive tutorials using AWS? GCP has an interactive tutorial engine and the code in `BackToBasics-Hacktoberfest/cloud-computing/google-cloud/cloud-run-website/` uses the same. To try it out (If you have a GCP account) all you have to do is click on open in Google Cloud Shell. It takes care of the rest. It will be great if something similar is there for AWS too.
