### ISSUE TITLE
PHP basics code examples

### ISSUE THREAD

**Issue by rid17pawar** [mahawiki/BackToBasics-Hacktoberfest#7]
I want to contribute by adding PHP basics code examples in this repository, which will be useful for beginners to learn PHP.

**Comment by APratham** [comment]
Sure that sounds wonderful. Please go ahead. Make sure you add a separate folder /PHP and then add all your code in that. You will also need to add a README for people to understand how to use the code samples

**Comment by rid17pawar** [comment]
Ok thanks
